"""empty message

Revision ID: 1402a9a4e97e
Revises: None
Create Date: 2016-03-05 11:27:42.836345

"""

# revision identifiers, used by Alembic.
revision = '1402a9a4e97e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('convener', sa.String(length=64), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conference_session')
    ### end Alembic commands ###
