"""empty message

Revision ID: acc0569b1d62
Revises: 1217a2e3ce7e
Create Date: 2016-03-05 11:49:33.383279

"""

# revision identifiers, used by Alembic.
revision = 'acc0569b1d62'
down_revision = '1217a2e3ce7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conference_location')
    ### end Alembic commands ###
