"""empty message

Revision ID: d4c97008629a
Revises: None
Create Date: 2016-03-05 17:44:18.497657

"""

# revision identifiers, used by Alembic.
revision = 'd4c97008629a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conference_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_name', sa.String(length=64), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['conference_location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_name')
    )
    op.create_table('conference_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('convener', sa.String(length=64), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['conference_space.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conference_session')
    op.drop_table('conference_space')
    op.drop_table('conference_location')
    ### end Alembic commands ###
