"""empty message

Revision ID: e0a59d9b65e7
Revises: acc0569b1d62
Create Date: 2016-03-05 12:02:34.594048

"""

# revision identifiers, used by Alembic.
revision = 'e0a59d9b65e7'
down_revision = 'acc0569b1d62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conference_session', 'conference_space', ['space_id'], ['id'])
    op.create_foreign_key(None, 'conference_space', 'conference_location', ['location_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conference_space', type_='foreignkey')
    op.drop_constraint(None, 'conference_session', type_='foreignkey')
    ### end Alembic commands ###
